import Head from "next/head";
import { useContext } from "react";
import GiftSection from "../components/Gift";
import Header from "../components/Header";
import Intro from "../components/Intro";
import RecentSection from "../components/RecentArticlesSections";
import Footer from "../components/Who";
import { themeContext } from "../context/context";

export default function Home() {
  const { theme } = useContext(themeContext);
  return (
    <div
      dir="rtl"
      className={`${
        theme === "light" ? "bg-[#ddd] text-black" : "bg-[#36263f] "
      } font-noto min-h-screen max-w-screen`}
    >
      <Head>
        <title>مدارج البرمجة</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <Intro />

        <hr
          className={`"text-black border-black ${
            theme === "light"
              ? " border-black bg-black text-black"
              : " border-white bg-white text-white"
          }
       `}
        ></hr>
        <RecentSection />

        <hr
          className={`"text-black border-black ${
            theme === "light"
              ? " border-black bg-black text-black"
              : " border-white bg-white text-white"
          }
       `}
        ></hr>
        <GiftSection />
        <hr
          className={`"text-black border-black ${
            theme === "light"
              ? " border-black bg-black text-black"
              : " border-white bg-white text-white"
          }
       `}
        ></hr>
        <Footer />
      </div>
    </div>
  );
}
