import Head from "next/head";
import GiftSection from "../components/Gift";
import HR from "../components/HR";
import Intro from "../components/Intro";
import RecentSection from "../components/RecentArticlesSections";

export default function Home() {
  return (
    <div>
      <Head>
        <title>مدارج البرمجة</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Intro />

        <HR />

        <RecentSection />

        <HR />
        <GiftSection />
        <HR />
      </div>
    </div>
  );
}
