import Head from "next/head";
import { useContext } from "react";
import Header from "../components/Header";
import Intro from "../components/Intro";
import { themeContext } from "../context/context";

export default function Home() {
  const { theme } = useContext(themeContext);
  return (
    <div
      dir="rtl"
      className={`${
        theme === "light" ? "bg-white text-black" : "bg-black "
      } font-noto min-h-screen`}
    >
      <Head>
        <title>مدارج البرمجة</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <Intro />
      </div>
    </div>
  );
}
